name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/${{ secrets.VPS_USER }}/cosmetics || { echo "Failed to cd"; exit 1; }

            git checkout master || { echo "git checkout failed"; exit 1; }
            git fetch origin || { echo "git fetch failed"; exit 1; }
            git pull origin master || { echo "git pull failed"; exit 1; }

            echo "Git updated successfully"

            sudo docker compose down --remove-orphans
            sudo docker compose up -d --build

            echo "Docker containers restarted"
